### ISSUE TITLE
How to get the MAD score?

### ISSUE THREAD

**Issue by Daizy97** [badchild0912/SmoothAdversarialExamples#1]
Thanks for your great work! I wonder how to calculate the MAD score of the adversarial image?

**Comment by hanwei0912** [comment]
> Thanks for your great work! I wonder how to calculate the MAD score of the adversarial image?

Hey～ The authors of MAD provide the code for it. You can find it at http://vision.eng.shizuoka.ac.jp/mod/url/view.php?id=54
