### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/pyrex/raid6/hzhang/2017-nips/test.csv'

### ISSUE THREAD

**Issue by Kitzzaaa** [badchild0912/SmoothAdversarialExamples#6]
What kind of file is this test.csv? Can you upload it?

**Comment by hanwei0912** [comment]
Please use your own imagenet data. If you really want this one, please check nips for adversarial competition 2017. Otherwise, you have the image name list but not the list.

**Comment by hanwei0912** [comment]
* not the images.
